<?php

namespace App\Helper;

class FormHelper
{
    public static function maritalStatusOptions() : array
    {
        return [
            'married'   => 'Married',
            'unmarried' => 'Unmarried',
            'divorced'  => 'Divorced',
            'widowed'   => 'Widowed',
        ];
    }

    public static function genderOptions() : array
    {
        return [
            'Male'          => 'Male',
            'Female'        => 'Female',
            'Transgender'   => 'Transgender',
        ];
    }

    public static function religionOptions() : array
    {
        return [
            'Islam'     => 'Islam',
            'Hinduism'  => 'Hinduism',
            'Buddhism'  => 'Buddhism',
            'Christian' => 'Christian',
        ];
    }

    public static function bloodGroupOptions() : array
    {
        return [
            'A+'    => 'A+',
            'A-'    => 'A-',
            'B+'    => 'B+',
            'B-'    => 'B-',
            'O+'    => 'O+',
            'O-'    => 'O-',
            'AB+'   => 'AB+',
            'AB-'   => 'AB-',
        ];
    }

    public static function jobNatureOptions() : array
    {
        return [
            'Consultant'    => 'Consultant',
            'Permanent'     => 'Permanent',
            'Part-Time'     => 'Part-Time',
            'Full-Time'     => 'Full-Time',
            'Contractual'   => 'Contractual',
            'Intern'        => 'Intern',
        ];
    }

    public static function jobLocationOptions() : array
    {
        return [
            'head-office'       => 'Head Office',
            'territory-office'  => 'Territory Office',
            'regional-office'   => 'Regional Office',
            'zonal-office'      => 'Zonal Office',
            'area-office'       => 'Area Office',
            'branch-office'     => 'Branch Office',
            'field-operation'   => 'Field Operation',
        ];
    }

    public static function recruitmentTypeOptions() : array
    {
        return [
            'Direct Recruitment'            => 'Direct Recruitment',
            'Agency Recruitment'            => 'Agency Recruitment',
            'Internal Recruitment'          => 'Internal Recruitment',
            'Campus Recruitment'            => 'Campus Recruitment',
            'Walk-in Recruitment'           => 'Walk-in Recruitment',
            'Online/E-Recruitment'          => 'Online/E-Recruitment',
            'Referral Recruitment'          => 'Referral Recruitment',
            'Bulk/Mass Recruitment'         => 'Bulk/Mass Recruitment',
            'Project Recruitment'           => 'Project Recruitment',
            'Diversity Hiring'              => 'Diversity Hiring',
            'Apprenticeship/Trainee Hiring' => 'Apprenticeship/Trainee Hiring',
        ];
    }

    public static function professionalSpecialityOptions() : array
    {
        return [
            'Software Engineering'                  => 'Software Engineering',
            'Web Development'                       => 'Web Development',
            'Mobile App Development'                => 'Mobile App Development',
            'Backend Development'                   => 'Backend Development',
            'Frontend Development'                  => 'Frontend Development',
            'Full Stack Development'                => 'Full Stack Development',
            'Database Administration'               => 'Database Administration',
            'System Administration'                 => 'System Administration',
            'IT Support'                            => 'IT Support',
            'DevOps Engineering'                    => 'DevOps Engineering',
            'Cloud Computing (AWS)'                 => 'Cloud Computing (AWS)',
            'Cloud Computing (Azure)'               => 'Cloud Computing (Azure)',
            'Cloud Computing (GCP)'                 => 'Cloud Computing (GCP)',
            'Cloud Computing (Alibaba)'             => 'Cloud Computing (Alibaba)',

            'Cyber Security'                        => 'Cyber Security',
            'Data Science'                          => 'Data Science',
            'Data Analysis'                         => 'Data Analysis',
            'Business Intelligence'                 => 'Business Intelligence',
            'Machine Learning'                      => 'Machine Learning',
            'Artificial Intelligence'               => 'Artificial Intelligence',
            'Data Engineering'                      => 'Data Engineering',
            'Big Data Analytics'                    => 'Big Data Analytics',

            'UI/UX Design'                          => 'UI/UX Design',
            'Graphic Design'                        => 'Graphic Design',
            'Motion Graphics'                       => 'Motion Graphics',
            'Video Editing'                         => 'Video Editing',
            '3D Modeling and Animation'             => '3D Modeling and Animation',
            'Product Design'                        => 'Product Design',
            'Branding and Identity Design'          => 'Branding and Identity Design',

            'Project Management'                    => 'Project Management',
            'Product Management'                    => 'Product Management',
            'Operations Management'                 => 'Operations Management',
            'Business Analysis'                     => 'Business Analysis',
            'Strategic Planning'                    => 'Strategic Planning',
            'Business Development'                  => 'Business Development',
            'Entrepreneurship'                      => 'Entrepreneurship',

            'Accounting'                            => 'Accounting',
            'Financial Analysis'                    => 'Financial Analysis',
            'Auditing'                              => 'Auditing',
            'Taxation'                              => 'Taxation',
            'Banking and Finance'                   => 'Banking and Finance',
            'Investment Analysis'                   => 'Investment Analysis',
            'Payroll Management'                    => 'Payroll Management',

            'Digital Marketing'                     => 'Digital Marketing',
            'Social Media Marketing'                => 'Social Media Marketing',
            'Content Writing'                       => 'Content Writing',
            'SEO (Search Engine Optimization)'      => 'SEO (Search Engine Optimization)',
            'SEM/PPC Advertising'                   => 'SEM/PPC Advertising',
            'Brand Management'                      => 'Brand Management',
            'Public Relations (PR)'                 => 'Public Relations (PR)',
            'Email Marketing'                       => 'Email Marketing',

            'Corporate Law'                         => 'Corporate Law',
            'Contract Law'                          => 'Contract Law',
            'Legal Advisory'                        => 'Legal Advisory',
            'Compliance Management'                 => 'Compliance Management',
            'Human Rights Law'                      => 'Human Rights Law',
            'Intellectual Property Law'             => 'Intellectual Property Law',

            'General Medicine'                      => 'General Medicine',
            'Nursing'                               => 'Nursing',
            'Pharmacy'                              => 'Pharmacy',
            'Medical Laboratory Technology'         => 'Medical Laboratory Technology',
            'Radiology'                             => 'Radiology',
            'Public Health'                         => 'Public Health',
            'Physiotherapy'                         => 'Physiotherapy',

            'Teaching (Primary/Secondary)'          => 'Teaching (Primary/Secondary)',
            'Higher Education Lecturer'             => 'Higher Education Lecturer',
            'Curriculum Development'                => 'Curriculum Development',
            'Educational Technology'                => 'Educational Technology',
            'Training and Development'              => 'Training and Development',
            'Academic Research'                     => 'Academic Research',

            'Civil Engineering'                     => 'Civil Engineering',
            'Mechanical Engineering'                => 'Mechanical Engineering',
            'Electrical Engineering'                => 'Electrical Engineering',
            'Electronics Engineering'               => 'Electronics Engineering',
            'Industrial Engineering'                => 'Industrial Engineering',
            'Architecture'                          => 'Architecture',
            'Construction Management'               => 'Construction Management',

            'Network Engineering'                   => 'Network Engineering',
            'System Architecture'                   => 'System Architecture',
            'Cloud Architecture'                    => 'Cloud Architecture',
            'IT Infrastructure Management'          => 'IT Infrastructure Management',
            'Telecom Engineering'                   => 'Telecom Engineering',

            'Scientific Research'                   => 'Scientific Research',
            'Product Research'                      => 'Product Research',
            'Laboratory Research'                   => 'Laboratory Research',
            'Innovation Management'                 => 'Innovation Management',
            'Technical Writing'                     => 'Technical Writing',

            'Human Resource Management'             => 'Human Resource Management',
            'Recruitment and Talent Acquisition'    => 'Recruitment and Talent Acquisition',
            'Office Administration'                 => 'Office Administration',
            'Employee Relations'                    => 'Employee Relations',
            'Training and Development (HR)'         => 'Training and Development (HR)',

            'Supply Chain Management'               => 'Supply Chain Management',
            'Procurement'                           => 'Procurement',
            'Inventory Management'                  => 'Inventory Management',
            'Warehouse Management'                  => 'Warehouse Management',
            'Logistics Coordination'                => 'Logistics Coordination',
        ];
    }

    public static function educationDegreeOptions() : array
    {
        return [
            'Illiterate'            => 'Illiterate',
            'PSC-Primary'           => 'PSC-Primary',
            'JSC-Junior-Secondary'  => 'JSC-Junior-Secondary',
            'SSC-Secondary'         => 'SSC-Secondary',
            'SSC_Vocational'        => 'SSC-Vocational',
            'SSC_Equivalent'        => 'SSC_Equivalent',
            'Diploma'               => 'Diploma',
            'HSC-Higher-Secondary'  => 'HSC-Higher-Secondary',
            'HSC-Vocational'        => 'HSC-Vocational',
            'HSC-Equivalent'        => 'HSC-Equivalent',
            'Dakhil'                => 'Dakhil',
            'Dakhil-Vocational'     => 'Dakhil-Vocational',
            'Alim'                  => 'Alim',
            'Alim-Vocational'       => 'Alim-Vocational',
            'OLevel-Cambridge'      => 'OLevel-Cambridge',
            'ALevel-SrCambridge'    => 'ALevel-SrCambridge',
            'BSc'                   => 'BSc',
            'Honors'                => 'Honors',
            'Masters'               => 'Masters',
            'MSc'                   => 'MSc',
            'MA'                    => 'MA',
            'MCom'                  => 'MCom',
            'Fazil'                 => 'Fazil',
            'Kamil'                 => 'Kamil',
            'BBA'                   => 'BBA',
            'MBBS'                  => 'MBBS',
            'BDS'                   => 'BDS',
            'MBA'                   => 'MBA',
            'LLB'                   => 'LLB',
            'LLM'                   => 'LLM',
            'MPhil'                 => 'MPhil',
            'PhD'                   => 'PhD',
            'Other'                 => 'Other',
        ];
    }

    public static function occupationOptions() : array
    {
        return [
            'Doctor' => 'Doctor',
            'Surgeon' => 'Surgeon',
            'Dentist' => 'Dentist',
            'Nurse' => 'Nurse',
            'Pharmacist' => 'Pharmacist',
            'Physiotherapist' => 'Physiotherapist',
            'Psychologist' => 'Psychologist',
            'Psychiatrist' => 'Psychiatrist',
            'Optometrist' => 'Optometrist',
            'Veterinarian' => 'Veterinarian',
            'Medical Laboratory Technologist' => 'Medical Laboratory Technologist',
            'Radiologist' => 'Radiologist',
            'Midwife' => 'Midwife',
            'Paramedic' => 'Paramedic',
            'Occupational Therapist' => 'Occupational Therapist',
            'Speech Therapist' => 'Speech Therapist',
            'Nutritionist' => 'Nutritionist',
            'Medical Assistant' => 'Medical Assistant',
            'Civil Engineer' => 'Civil Engineer',
            'Mechanical Engineer' => 'Mechanical Engineer',
            'Electrical Engineer' => 'Electrical Engineer',
            'Chemical Engineer' => 'Chemical Engineer',
            'Software Engineer' => 'Software Engineer',
            'Aerospace Engineer' => 'Aerospace Engineer',
            'Environmental Engineer' => 'Environmental Engineer',
            'Industrial Engineer' => 'Industrial Engineer',
            'Petroleum Engineer' => 'Petroleum Engineer',
            'Mining Engineer' => 'Mining Engineer',
            'Marine Engineer' => 'Marine Engineer',
            'Biomedical Engineer' => 'Biomedical Engineer',
            'Structural Engineer' => 'Structural Engineer',
            'Robotics Engineer' => 'Robotics Engineer',
            'Software Developer' => 'Software Developer',
            'Web Developer' => 'Web Developer',
            'Mobile App Developer' => 'Mobile App Developer',
            'Data Scientist' => 'Data Scientist',
            'Data Analyst' => 'Data Analyst',
            'AI Engineer' => 'AI Engineer',
            'Machine Learning Engineer' => 'Machine Learning Engineer',
            'Cybersecurity Analyst' => 'Cybersecurity Analyst',
            'Network Engineer' => 'Network Engineer',
            'System Administrator' => 'System Administrator',
            'Cloud Engineer' => 'Cloud Engineer',
            'DevOps Engineer' => 'DevOps Engineer',
            'Database Administrator' => 'Database Administrator',
            'UI/UX Designer' => 'UI/UX Designer',
            'IT Support Specialist' => 'IT Support Specialist',
            'Blockchain Developer' => 'Blockchain Developer',
            'Ethical Hacker' => 'Ethical Hacker',
            'AR/VR Developer' => 'AR/VR Developer',
            'Bioinformatics Specialist' => 'Bioinformatics Specialist',
            'IT Technician' => 'IT Technician',
            'Teacher' => 'Teacher',
            'Professor' => 'Professor',
            'Lecturer' => 'Lecturer',
            'Tutor' => 'Tutor',
            'School Principal' => 'School Principal',
            'Librarian' => 'Librarian',
            'Education Consultant' => 'Education Consultant',
            'Curriculum Developer' => 'Curriculum Developer',
            'Special Education Teacher' => 'Special Education Teacher',
            'Accountant' => 'Accountant',
            'Auditor' => 'Auditor',
            'Financial Analyst' => 'Financial Analyst',
            'Investment Banker' => 'Investment Banker',
            'Economist' => 'Economist',
            'Insurance Agent' => 'Insurance Agent',
            'Financial Planner' => 'Financial Planner',
            'Tax Consultant' => 'Tax Consultant',
            'Business Analyst' => 'Business Analyst',
            'Management Consultant' => 'Management Consultant',
            'Banker' => 'Banker',
            'Consultant' => 'Consultant',
            'Entrepreneur' => 'Entrepreneur',
            'Business Owner' => 'Business Owner',
            'Small Business Owner' => 'Small Business Owner',
            'Procurement Officer' => 'Procurement Officer',
            'Compliance Officer' => 'Compliance Officer',
            'Risk Manager' => 'Risk Manager',
            'Lawyer' => 'Lawyer',
            'Judge' => 'Judge',
            'Prosecutor' => 'Prosecutor',
            'Police Officer' => 'Police Officer',
            'Detective' => 'Detective',
            'Firefighter' => 'Firefighter',
            'Customs Officer' => 'Customs Officer',
            'Prison Officer' => 'Prison Officer',
            'Military Officer' => 'Military Officer',
            'Soldier' => 'Soldier',
            'Diplomat' => 'Diplomat',
            'Intelligence Officer' => 'Intelligence Officer',
            'Civil Servant' => 'Civil Servent',
            'Administrative Officer' => 'Administrative Officer',
            'City Planner' => 'City Planner',
            'Census Officer' => 'Census Officer',
            'Tax Officer' => 'Tax Officer',
            'Immigration Officer' => 'Immigration Officer',
            'Policy Analyst' => 'Policy Analyst',
            'Biologist' => 'Biologist',
            'Chemist' => 'Chemist',
            'Physicist' => 'Physicist',
            'Geologist' => 'Geologist',
            'Astronomer' => 'Astronomer',
            'Meteorologist' => 'Meteorologist',
            'Oceanographer' => 'Oceanographer',
            'Geneticist' => 'Geneticist',
            'Microbiologist' => 'Microbiologist',
            'Environmental Scientist' => 'Environmental Scientist',
            'Climate Risk Analyst' => 'Climate Risk Analyst',
            'Actor' => 'Actor',
            'Actress' => 'Actress',
            'Musician' => 'Musician',
            'Singer' => 'Singer',
            'Composer' => 'Composer',
            'Dancer' => 'Dancer',
            'Choreographer' => 'Choreographer',
            'Painter' => 'Painter',
            'Sculptor' => 'Sculptor',
            'Photographer' => 'Photographer',
            'Filmmaker' => 'Filmmaker',
            'Director' => 'Director',
            'Producer' => 'Producer',
            'Writer' => 'Writer',
            'Poet' => 'Poet',
            'Author' => 'Author',
            'Illustrator' => 'Illustrator',
            'Artist' => 'Artist',
            'Journalist' => 'Journalist',
            'News Reporter' => 'News Reporter',
            'Editor' => 'Editor',
            'Broadcaster' => 'Broadcaster',
            'Radio Host' => 'Radio Host',
            'TV Presenter' => 'TV Presenter',
            'Copywriter' => 'Copywriter',
            'Technical Writer' => 'Technical Writer',
            'Public Relations Specialist' => 'Public Relations Specialist',
            'Social Media Manager' => 'Social Media Manager',
            'Blogger' => 'Blogger',
            'YouTuber' => 'YouTuber',
            'Podcaster' => 'Podcaster',
            'Influencer' => 'Influencer',
            'Street Performer' => 'Street Performer',
            'Street Magician' => 'Street Magician',
            'Sales Representative' => 'Sales Representative',
            'Sales Manager' => 'Sales Manager',
            'Marketing Manager' => 'Marketing Manager',
            'Brand Manager' => 'Brand Manager',
            'Digital Marketer' => 'Digital Marketer',
            'SEO Specialist' => 'SEO Specialist',
            'Advertising Executive' => 'Advertising Executive',
            'Market Research Analyst' => 'Market Research Analyst',
            'Cashier' => 'Cashier',
            'Store Manager' => 'Store Manager',
            'Merchandiser' => 'Merchandiser',
            'Inventory Clerk' => 'Inventory Clerk',
            'Customer Service Representative' => 'Customer Service Representative',
            'Retail Sales Associate' => 'Retail Sales Associate',
            'Shopkeeper' => 'Shopkeeper',
            'Online Seller' => 'Online Seller',
            'Architect' => 'Architect',
            'Construction Manager' => 'Construction Manager',
            'Construction Worker' => 'Construction Worker',
            'Day Laborer' => 'Day Laborer',
            'Carpenter' => 'Carpenter',
            'Mason' => 'Mason',
            'Bricklayer' => 'Bricklayer',
            'Electrician' => 'Electrician',
            'Plumber' => 'Plumber',
            'Welder' => 'Welder',
            'Roofer' => 'Roofer',
            'Surveyor' => 'Surveyor',
            'Heavy Equipment Operator' => 'Heavy Equipment Operator',
            'Tile Setter' => 'Tile Setter',
            'Steel Fixer' => 'Steel Fixer',
            'Scaffolder' => 'Scaffolder',
            'Road Worker' => 'Road Worker',
            'Locksmith' => 'Locksmith',
            'Blacksmith' => 'Blacksmith',
            'Machinist' => 'Machinist',
            'CNC Machinist' => 'CNC Machinist',
            'Glazier' => 'Glazier',
            'Boilermaker' => 'Boilermaker',
            'HVAC Technician' => 'HVAC Technician',
            'Elevator Mechanic' => 'Elevator Mechanic',
            'Refrigeration Technician' => 'Refrigeration Technician',
            'Tailor' => 'Tailor',
            'Cobbler' => 'Cobbler',
            'Shoe Shiner' => 'Shoe Shiner',
            'Goldsmith' => 'Goldsmith',
            'Mechanic' => 'Mechanic',
            'Electric Appliance Repairer' => 'Electric Appliance Repairer',
            'Mobile Phone Repair Technician' => 'Mobile Phone Repair Technician',
            'Factory Worker' => 'Factory Worker',
            'Garment Worker' => 'Garment Worker',
            'Textile Worker' => 'Textile Worker',
            'Machine Operator' => 'Machine Operator',
            'Assembly Line Worker' => 'Assembly Line Worker',
            'Quality Inspector' => 'Quality Inspector',
            'Production Supervisor' => 'Production Supervisor',
            'Tool and Die Maker' => 'Tool and Die Maker',
            'Packaging Worker' => 'Packaging Worker',
            'Loading/Unloading Worker' => 'Loading/Unloading Worker',
            'Warehouse Worker' => 'Warehouse Worker',
            'Pilot' => 'Pilot',
            'Flight Attendant' => 'Flight Attendant',
            'Air Traffic Controller' => 'Air Traffic Controller',
            'Logistics Coordinator' => 'Logistics Coordinator',
            'Car Driver' => 'Car Driver',
            'Taxi Driver' => 'Taxi Driver',
            'Bus Driver' => 'Bus Driver',
            'Truck Driver' => 'Truck Driver',
            'Train Driver' => 'Train Driver',
            'Auto-rickshaw Driver' => 'Auto-rickshaw Driver',
            'Rickshaw Puller' => 'Rickshaw Puller',
            'Van Driver' => 'Van Driver',
            'Boatman' => 'Boatman',
            'Ferry Operator' => 'Ferry Operator',
            'Ship Captain' => 'Ship Captain',
            'Sailor' => 'Sailor',
            'Delivery Man' => 'Delivery Man',
            'Courier' => 'Courier',
            'Bus Helper' => 'Bus Helper',
            'Bus Conductor' => 'Bus Conductor',
            'Ticket Checker' => 'Ticket Checker',
            'Parking Attendant' => 'Parking Attendant',
            'Porter' => 'Porter',
            'Coolie' => 'Coolie',
            'Handcart Puller' => 'Handcart Puller',
            'Postal Worker' => 'Postal Worker',
            'Farmer' => 'Farmer',
            'Farm Laborer' => 'Farm Laborer',
            'Rancher' => 'Rancher',
            'Fisherman' => 'Fisherman',
            'Forester' => 'Forester',
            'Horticulturist' => 'Horculturist',
            'Agronomist' => 'Agronomist',
            'Beekeeper' => 'Beekeeper',
            'Dairy Farmer' => 'Dairy Farmer',
            'Poultry Farmer' => 'Poultry Farmer',
            'Chef' => 'Chef',
            'Cook' => 'Cook',
            'Baker' => 'Baker',
            'Waiter' => 'Waiter',
            'Waitress' => 'Waitress',
            'Bartender' => 'Bartender',
            'Dishwasher' => 'Dishwasher',
            'Kitchen Helper' => 'Kitchen Helper',
            'Hotel Worker' => 'Hotel Worker',
            'Hotel Manager' => 'Hotel Manager',
            'Receptionist' => 'Receptionist',
            'Tour Guide' => 'Tour Guide',
            'Travel Agent' => 'Travel Agent',
            'Event Planner' => 'Event Planner',
            'Catering Worker' => 'Catering Worker',
            'Restaurant Owner' => 'Restaurant Owner',
            'Tea Stall Owner' => 'Tea Stall Owner',
            'Barber' => 'Barber',
            'Hair Stylist' => 'Hair Stylist',
            'Hairdresser' => 'Hairdresser',
            'Beautician' => 'Beautician',
            'Makeup Artist' => 'Makeup Artist',
            'Massage Therapist' => 'Massage Therapist',
            'Personal Trainer' => 'Personal Trainer',
            'Fitness Instructor' => 'Fitness Instructor',
            'Fitness Coach' => 'Fitness Coach',
            'Life Coach' => 'Life Coach',
            'Childcare Worker' => 'Childcare Worker',
            'Housekeeper' => 'Housekeeper',
            'Domestic Worker' => 'Domestic Worker',
            'Maid' => 'Maid',
            'Caregiver' => 'Caregiver',
            'Nanny' => 'Nanny',
            'Gardener' => 'Gardener',
            'Watchman' => 'Watchman',
            'Security Guard' => 'Security Guard',
            'Janitor' => 'Janitor',
            'Cleaner' => 'Cleaner',
            'Graphic Designer' => 'Graphic Designer',
            'Fashion Designer' => 'Fashion Designer',
            'Interior Designer' => 'Interior Designer',
            'Industrial Designer' => 'Industrial Designer',
            'Product Designer' => 'Product Designer',
            'Animator' => 'Animator',
            'Game Designer' => 'Game Designer',
            'Athlete' => 'Athlete',
            'Coach' => 'Coach',
            'Referee' => 'Referee',
            'Sports Analyst' => 'Sports Analyst',
            'Sports Manager' => 'Sports Manager',
            'Renewable Energy Technician' => 'Renewable Energy Technician',
            'Solar Installer' => 'Solar Installer',
            'Wind Turbine Technician' => 'Wind Turbine Technician',
            'Conservation Officer' => 'Conservation Officer',
            'Recycling Specialist' => 'Recycling Specialist',
            'Sustainability Consultant' => 'Sustainability Consultant',
            'Street Vendor' => 'Street Vendor',
            'Hawker' => 'Hawker',
            'Fruit Seller' => 'Fruit Seller',
            'Vegetable Seller' => 'Vegetable Seller',
            'Fish Seller' => 'Fish Seller',
            'Meat Seller' => 'Meat Seller',
            'Flower Seller' => 'Flower Seller',
            'Book Seller' => 'Book Seller',
            'Clothing Seller' => 'Clothing Seller',
            'Electronics Seller' => 'Electronics Seller',
            'Mobile Phone Shop Owner' => 'Mobile Phone Shop Owner',
            'Toy Seller' => 'Toy Seller',
            'Ice Cream Vendor' => 'Ice Cream Vendor',
            'Newspaper Vendor' => 'Newspaper Vendor',
            'Grocery Store Owner' => 'Grocery Store Owner',
            'Beggar' => 'Beggar',
            'Waste Collector' => 'Waste Collector',
            'Scrap Collector' => 'Scrap Collector',
            'Rag Picker' => 'Rag Picker',
            'Drone Operator' => 'Drone Operator',
            'AI Prompt Engineer' => 'AI Prompt Engineer',
        ];
    }
}
